"""create users

Revision ID: 13cde3114cd4
Revises: 
Create Date: 2025-06-08 14:06:20.884423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13cde3114cd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coworking',
    sa.Column('coworking_id', sa.Integer(), nullable=False),
    sa.Column('coworking_location', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('coworking_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.String(length=1000), nullable=True),
    sa.Column('event_date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('event_location', sa.String(length=100), nullable=False),
    sa.Column('event_max_seats', sa.Integer(), nullable=False),
    sa.Column('event_photo', sa.String(length=512), nullable=False),
    sa.Column('event_host', sa.String(length=255), nullable=False),
    sa.Column('event_price', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('news_photo', sa.String(length=512), nullable=False),
    sa.Column('news_text', sa.String(length=5000), nullable=False),
    sa.Column('news_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('news_title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event_registration',
    sa.Column('event_registration_id', sa.Integer(), nullable=False),
    sa.Column('event_registration_user_id', sa.Integer(), nullable=False),
    sa.Column('event_registration_event_id', sa.Integer(), nullable=False),
    sa.Column('event_reg_date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('event_reg_email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['event_registration_event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['event_registration_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_registration_id')
    )
    op.create_table('seat',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('seat_coworking_id', sa.Integer(), nullable=False),
    sa.Column('seat_index', sa.Integer(), nullable=False),
    sa.Column('seat_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seat_coworking_id'], ['coworking.coworking_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_user_id', sa.Integer(), nullable=False),
    sa.Column('booking_seat_id', sa.Integer(), nullable=False),
    sa.Column('booking_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('booking_end', sa.TIMESTAMP(), nullable=False),
    sa.Column('booking_email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['booking_seat_id'], ['seat.seat_id'], ),
    sa.ForeignKeyConstraint(['booking_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    sa.UniqueConstraint('booking_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('seat')
    op.drop_table('event_registration')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('event')
    op.drop_table('coworking')
    # ### end Alembic commands ###
