"""coworking

Revision ID: 6f2f8c46e450
Revises: 13cde3114cd4
Create Date: 2025-06-12 13:23:55.995132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2f8c46e450'
down_revision: Union[str, None] = '13cde3114cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coworking', sa.Column('is_conference', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coworking', 'is_conference')
    # ### end Alembic commands ###
