"""init

Revision ID: 841a0d53a375
Revises: e84353a928e3
Create Date: 2025-06-04 14:29:02.442644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841a0d53a375'
down_revision: Union[str, None] = 'e84353a928e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_history')
    op.alter_column('event', 'event_photo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('news', 'news_photo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'news_photo',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('event', 'event_photo',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('event_history',
    sa.Column('event_history_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_history_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_history_event_id'], ['event.event_id'], name='event_history_event_history_event_id_fkey'),
    sa.ForeignKeyConstraint(['event_history_user_id'], ['user.id'], name='event_history_event_history_user_id_fkey')
    )
    # ### end Alembic commands ###
